version: '3.7'

services:
  db-adm:
    image: mysql:8.0
    container_name: 'mysql-adm'
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  #app-administrators:
    #build: .
    #image: app-administrators:1.0
    #container_name: 'aplication-administrators'
    #restart: always
    #depends_on:
      #- db-adm
    #environment:
      #SPRING_DATASOURCE_URL: "jdbc:mysql://db-adm:3306/AdmDatabase?useTimezone=true&serverTimezone=UTC"
      #SPRING_DATASOURCE_USERNAME: root
      #SPRING_DATASOURCE_PASSWORD: 'admin'
      #SPRING_JPA_HIBERNATE_DDL_AUTO: update
    #ports:
      #- 8080:8080
    #networks:
      #- network-aplication 

#networks:
  #network-aplication: